export const USER_ACTIVE_MODULE_SUBMODULE = "USER_ACTIVE_MODULE_SUBMODULE";
export const SELECTED_SUBMODULE = "SELECTED_SUBMODULE";
export const SUBMODULE_1_DETAIL = "SUBMODULE_1_DETAIL";
export const SUBMODULE_2_DETAIL = "SUBMODULE_2_DETAIL";
